# Generated by Django 3.2.6 on 2021-08-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0002_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
