# Generated by Django 3.2.6 on 2021-09-06 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0004_pulsedairy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulsedairy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pulsedairy',
            name='temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
